### PR TITLE
Support card container view customizable viewpager example

### PR DESCRIPTION
**Pull request by swatiomar**

### CODE REVIEW

**Comment by luongvo** [comment]
@swatiomar it's not be good at all, so I did not make a PR yet

**Comment by swatiomar** [comment]
Sir, can any other library you know... As I want this....

**Comment by luongvo** [comment]
@swatiomar you can checkout our code at our forked repo for your using

**Comment by swatiomar** [comment]
Can you please share a link. I am not able to find it....

**Comment by luongvo** [comment]
@swatiomar @yuyakaido Can you close this PR from our forked repo `buddify`. I don't to make this PR cuz it's not finished yet and just for demonstration 🚲

**Comment by yuyakaido** [comment]
@luongvo ok! Thank you for your contribution!

**Pull request closed without merging**
