### PR TITLE
add two setting fields: useProportionalSwipe and canLastItemSwipe

### PR DESCRIPTION
**Pull request by wenhaiz**
`useProportionalSwipe` : whether to enable proportional swipe
`canLastItemSwipe` : can user swipe the last item

### CODE REVIEW

**Comment by mysterymanX1** [comment]
> `useProportionalSwipe` : whether to enable proportional swipe `canLastItemSwipe` : can user swipe the last item

hello that's good ,i need this,thanks

**Comment by mysterymanX1** [comment]
> `useProportionalSwipe` : whether to enable proportional swipe `canLastItemSwipe` : can user swipe the last item

i have some issue to ask you，can i have your email，thanks

**Comment by wenhaiz** [comment]
> > `useProportionalSwipe` : whether to enable proportional swipe `canLastItemSwipe` : can user swipe the last item
> 
> i have some issue to ask you，can i have your email，thanks

yes, my email is  wenhaiz.me@qq.com

**Comment by mysterymanX1** [comment]
hello

**Comment by mysterymanX1** [comment]
@wenhaiz i send for you ，can you help me，thanks

**Pull request closed without merging**
